# Generated by Django 3.2.9 on 2022-12-16 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('E1', models.IntegerField(default=0)),
                ('E1B_AK', models.IntegerField(default=0)),
                ('E1B_47', models.IntegerField(default=0)),
                ('E1_JOCKER', models.BooleanField(default=None, null=True)),
                ('E2', models.IntegerField(default=0)),
                ('E2B_AK', models.IntegerField(default=0)),
                ('E2B_47', models.IntegerField(default=0)),
                ('E2_JOCKER', models.BooleanField(default=None, null=True)),
                ('E3', models.IntegerField(default=0)),
                ('E3B_AK', models.IntegerField(default=0)),
                ('E3B_47', models.IntegerField(default=0)),
                ('E3_JOCKER', models.BooleanField(default=None, null=True)),
                ('E4', models.IntegerField(default=0)),
                ('E4B_AK', models.IntegerField(default=0)),
                ('E4B_47', models.IntegerField(default=0)),
                ('E4_JOCKER', models.BooleanField(default=None, null=True)),
                ('E5', models.IntegerField(default=0)),
                ('E5B_AK', models.IntegerField(default=0)),
                ('E5B_47', models.IntegerField(default=0)),
                ('E5_JOCKER', models.BooleanField(default=None, null=True)),
                ('E6', models.IntegerField(default=0)),
                ('E6B_AK', models.IntegerField(default=0)),
                ('E6B_47', models.IntegerField(default=0)),
                ('E6_JOCKER', models.BooleanField(default=None, null=True)),
                ('E7', models.IntegerField(default=0)),
                ('E7B_AK', models.IntegerField(default=0)),
                ('E7B_47', models.IntegerField(default=0)),
                ('E7_JOCKER', models.BooleanField(default=None, null=True)),
                ('E8', models.IntegerField(default=0)),
                ('E8B_AK', models.IntegerField(default=0)),
                ('E8B_47', models.IntegerField(default=0)),
                ('E8_JOCKER', models.BooleanField(default=None, null=True)),
                ('E9', models.IntegerField(default=0)),
                ('E9B_AK', models.IntegerField(default=0)),
                ('E9B_47', models.IntegerField(default=0)),
                ('E9_JOCKER', models.BooleanField(default=None, null=True)),
                ('E10', models.IntegerField(default=0)),
                ('E10B_AK', models.IntegerField(default=0)),
                ('E10B_47', models.IntegerField(default=0)),
                ('E10_JOCKER', models.BooleanField(default=None, null=True)),
                ('E11', models.IntegerField(default=0)),
                ('E11B_AK', models.IntegerField(default=0)),
                ('E11B_47', models.IntegerField(default=0)),
                ('E11_JOCKER', models.BooleanField(default=None, null=True)),
                ('E12', models.IntegerField(default=0)),
                ('E12B_AK', models.IntegerField(default=0)),
                ('E12B_47', models.IntegerField(default=0)),
                ('E12_JOCKER', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_prize', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
