# Generated by Django 3.2.9 on 2022-12-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='E10B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='E11B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='E12B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='E1B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='E2B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='E3B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='E4B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='E5B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='E6B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='E7B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='E8B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='E9B',
            field=models.IntegerField(default=0),
        ),
    ]
