# Generated by Django 3.2.9 on 2022-12-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jocker_image',
            field=models.ImageField(default='jocker.jpg', upload_to='jocker_pics'),
        ),
    ]
