# Generated by Django 3.2.9 on 2022-12-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_auto_20221214_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='E10_JOCKER',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='player',
            name='E11_JOCKER',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='player',
            name='E12_JOCKER',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='player',
            name='E1_JOCKER',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='player',
            name='E2_JOCKER',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='player',
            name='E3_JOCKER',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='player',
            name='E4_JOCKER',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='player',
            name='E5_JOCKER',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='player',
            name='E6_JOCKER',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='player',
            name='E7_JOCKER',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='player',
            name='E8_JOCKER',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='player',
            name='E9_JOCKER',
            field=models.BooleanField(default=None),
        ),
    ]
