# Generated by Django 3.2.9 on 2022-12-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0004_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(
                blank=True, help_text="Day of the event"
            ),
        ),
    ]
